version: '3.8'
services:
  app:
    image: openjdk:21-jdk-slim
    container_name: spring_PicPay
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 
    volumes:
      - ./target/API-PicPay-0.0.1-SNAPSHOT.jar:/app/app.jar

    working_dir: /app
    entrypoint: ["java", "-jar", "/app/app.jar"]
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: PicPay_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
